name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Check Python
        run: python --version

      - name: Check imports
        run: |
          python -c "import pandas"
          python -c "import sklearn"
          python -c "import fastapi"
          python -c "import pydantic"

      - name: Build Docker image
        run: docker build -t fraud-detection-api .